HotelProject/Models/Visitor.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HotelProject.Models
{
    public class Visitor
    {
        public Guid ID { get; set; }
        [Display(Name = "ФИО")]
        public string FullName { get; set; }
        [Display(Name = "Въезд")]
        [DataType(DataType.Date)]
        public DateTime ArrivalDate { get; set; }
        [Display(Name = "Выезд")]
        [DataType(DataType.Date)]
        public DateTime? DepartureDate { get; set; }

        public virtual Room Room { get; set; }
    }
}

HotelProject/Controllers/RoomsController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Data;
using HotelProject.Models;

namespace HotelProject.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index(string searchString)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                var rooms = _context.Rooms.Where(x => x.Type.ToString().Contains(searchString)
                                                      || (typeof(RoomType).GetMember(x.Type.ToString())[0].GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute).GetName().Contains(searchString)
                                                      || x.Number.ToString().Contains(searchString)
                                                      || x.NumberOfPlaces.ToString().Contains(searchString));

                return View(rooms.ToList());
            }

            return View(await _context.Rooms.Include(c => c.Visitors).ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Number,Type,NumberOfPlaces")]
            Room room)
        {
            if (ModelState.IsValid)
            {
                room.IsBusy = false;
                room.ID = Guid.NewGuid();
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(room);
        }

        //// GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,Number,Type,NumberOfPlaces,IsBusy")]
            Room room)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //room.IsBusy = _context.Rooms.SingleOrDefault(x => x.ID == room.ID).IsBusy;
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.ID))
                    {
                        return NotFound();
                    }

                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(Guid id)
        {
            return _context.Rooms.Any(e => e.ID == id);
        }
    }
}

HotelProject/Controllers/VisitorsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Data;
using HotelProject.Models;

namespace HotelProject.Controllers
{
    public class VisitorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VisitorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Visitors
        public async Task<IActionResult> Index(string searchString)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredVisitors = _context.Visitors.Include(c => c.Room).Where(x => x.FullName.Contains(searchString)
                                                      || x.ArrivalDate.ToString("dd.MM.yyyy").Contains(searchString)
                                                      || x.DepartureDate.ToString().Contains(searchString));

                return View(filteredVisitors.ToList());
            }
            List<Visitor> visitors = _context.Visitors
                .Include(c => c.Room)
                .ToList();

            return View(visitors);
        }

        // GET: Visitors/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visitor = await _context.Visitors.Include(c => c.Room)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (visitor == null)
            {
                return NotFound();
            }

            return View(visitor);
        }

        // GET: Visitors/Create
        public IActionResult Create(Guid roomId)
        {
            ViewBag.roomID = roomId;
            return View();
        }

        // POST: Visitors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid roomId, [Bind("ID,FullName,ArrivalDate")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                visitor.ID = Guid.NewGuid();
                visitor.Room = _context.Rooms.SingleOrDefault(x => x.ID == roomId);
                visitor.DepartureDate = null;
                _context.Add(visitor);
                _context.Rooms.Single(x => x.ID == roomId).IsBusy = true;
                _context.Update(_context.Rooms.Single(x => x.ID == roomId));

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(visitor);
        }

        // GET: Visitors/Edit/5
        public IActionResult Edit(Guid? roomId)
        {
            if (roomId == null)
            {
                return NotFound();
            }

            var visitor = _context.Visitors.Include(c => c.Room).SingleOrDefault(x => x.Room.ID == roomId && x.DepartureDate == null);
            if (visitor == null)
                return NotFound();


            visitor.DepartureDate = DateTime.UtcNow;
            visitor.Room.IsBusy = !visitor.Room.IsBusy;
            _context.Update(visitor);
            _context.SaveChangesAsync();

            double cost = 0;

            switch (visitor.Room.Type)
            {
                case RoomType.Standart:
                    cost += 100;
                    break;
                case RoomType.JuniorSuite:
                    cost += 200;
                    break;
                case RoomType.Lux:
                    cost += 300;
                    break;
            }

            cost += cost * 0.4 * (visitor.Room.NumberOfPlaces - 1);

            cost *= (visitor.DepartureDate - visitor.ArrivalDate).Value.Days;


            string result = $"Номер класса: {(typeof(RoomType).GetMember(visitor.Room.Type.ToString())[0].GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute)?.GetName()}; \r\n" +
                            $"Колличество мест - {visitor.Room.NumberOfPlaces}; \r\n" +
                            $"Колличество прожитых дней - {(visitor.DepartureDate - visitor.ArrivalDate).Value.Days}; \r\n" +
                            $"Полная стоимость проживания - {cost} у.е. \r\n";

            ViewBag.result = result;

            return View();
        }

       // GET: Visitors/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visitor = await _context.Visitors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (visitor == null)
            {
                return NotFound();
            }

            return View(visitor);
        }

        // POST: Visitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var visitor = await _context.Visitors.FindAsync(id);
            _context.Visitors.Remove(visitor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitorExists(Guid id)
        {
            return _context.Visitors.Any(e => e.ID == id);
        }
    }
}

HotelProject/Views/Visitors/Create.cshtml
@using System.Globalization
@model HotelProject.Models.Visitor

@{
    ViewData["Title"] = "Заселение";
}

<h2>Заселение</h2>

<h4>Данные о госте</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">  
                <label asp-for="ArrivalDate" class="control-label"></label>
                <input asp-for="ArrivalDate" class="form-control" value="@DateTime.UtcNow.ToString("yyyy-MM-dd")"/>
                <span asp-validation-for="ArrivalDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Заселить" asp-route-roomId=@ViewBag.roomID class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Rooms" asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelProject/Views/Visitors/Delete.cshtml
@model HotelProject.Models.Visitor

@{
    ViewData["Title"] = "Удаление посетителя";
}

<h2>Удаление посетителя</h2>

<h3>Вы действительно хотите удалить этого посетителя?</h3>
<div>
    <h4>Посетитель</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Room.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Room.Number)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

HotelProject/Views/Visitors/Details.cshtml
@model HotelProject.Models.Visitor

@{
    ViewData["Title"] = "Информация о посетителе";
}

<h2>Информация о посетителе</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Room.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Room.Number)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Назад</a>
</div>

HotelProject/Views/Visitors/Edit.cshtml
@{
    ViewData["Title"] = "Выезд";
}

<h2>Выезд</h2>

<h4>Чек</h4>

<pre>@ViewBag.result</pre>


<div>
<a asp-action="Index">Назад</a>
</div>

HotelProject/Views/Visitors/Index.cshtml
@model IEnumerable<HotelProject.Models.Visitor>

@{
    ViewData["Title"] = "Посетители";
}

<h2>Посетители</h2>

@using (Html.BeginForm())
{
    <p>
        Найти: @Html.TextBox("SearchString")
        <input type="submit" value="Поиск" />
    </p>
}

<table id="VisitorsTable" class="table">
    <thead>
        <tr>
            <th onclick="sortTable(0)">
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th onclick="sortTable(1)">
                @Html.DisplayNameFor(model => model.ArrivalDate)
            </th>
            <th onclick="sortTable(2)">
                @Html.DisplayNameFor(model => model.DepartureDate)
            </th>
            <th onclick="sortTable(3)">
                @Html.DisplayNameFor(model => model.Room.Number)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.Number)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">Детали</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function sortTable(n) {
        var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("VisitorsTable");
        switching = true;
        dir = "asc";
        while (switching) {
            switching = false;
            rows = table.rows;
            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }
            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchcount++;
            } else {
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
</script>