HotelProject/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HotelProject.Models
{
    public class Room
    {
        public Guid ID { get; set; }
        [Display(Name = "Номер")]
        public int Number { get; set; }
        [Display(Name = "Тип")]
        public RoomType Type { get; set; }
        [Display(Name = "Места")]
        public int NumberOfPlaces { get; set; }
        [Display(Name = "Занятость")]
        public bool IsBusy { get; set; }

        public virtual ICollection<Visitor> Visitors { get; set; }
    }

    public enum RoomType
    {
        [Display(Name = "Стандартный")]
        Standart,
        [Display(Name = "Люкс")]
        Lux,
        [Display(Name = "Полулюкс")]
        JuniorSuite
    }

    public class RoomTypeViewModel
    {
        public RoomType Type { get; set; }
    }
}

HotelProject/Controllers/RoomsController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Data;
using HotelProject.Models;

namespace HotelProject.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index(string searchString)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                var rooms = _context.Rooms.Where(x => x.Type.ToString().Contains(searchString)
                                                      || (typeof(RoomType).GetMember(x.Type.ToString())[0].GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute).GetName().Contains(searchString)
                                                      || x.Number.ToString().Contains(searchString)
                                                      || x.NumberOfPlaces.ToString().Contains(searchString));

                return View(rooms.ToList());
            }

            return View(await _context.Rooms.Include(c => c.Visitors).ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Number,Type,NumberOfPlaces")]
            Room room)
        {
            if (ModelState.IsValid)
            {
                room.IsBusy = false;
                room.ID = Guid.NewGuid();
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(room);
        }

        //// GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,Number,Type,NumberOfPlaces,IsBusy")]
            Room room)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //room.IsBusy = _context.Rooms.SingleOrDefault(x => x.ID == room.ID).IsBusy;
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.ID))
                    {
                        return NotFound();
                    }

                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(Guid id)
        {
            return _context.Rooms.Any(e => e.ID == id);
        }
    }
}

HotelProject/Controllers/VisitorsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HotelProject.Data;
using HotelProject.Models;

namespace HotelProject.Controllers
{
    public class VisitorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VisitorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Visitors
        public async Task<IActionResult> Index(string searchString)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredVisitors = _context.Visitors.Include(c => c.Room).Where(x => x.FullName.Contains(searchString)
                                                      || x.ArrivalDate.ToString("dd.MM.yyyy").Contains(searchString)
                                                      || x.DepartureDate.ToString().Contains(searchString));

                return View(filteredVisitors.ToList());
            }
            List<Visitor> visitors = _context.Visitors
                .Include(c => c.Room)
                .ToList();

            return View(visitors);
        }

        // GET: Visitors/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visitor = await _context.Visitors.Include(c => c.Room)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (visitor == null)
            {
                return NotFound();
            }

            return View(visitor);
        }

        // GET: Visitors/Create
        public IActionResult Create(Guid roomId)
        {
            ViewBag.roomID = roomId;
            return View();
        }

        // POST: Visitors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid roomId, [Bind("ID,FullName,ArrivalDate")] Visitor visitor)
        {
            if (ModelState.IsValid)
            {
                visitor.ID = Guid.NewGuid();
                visitor.Room = _context.Rooms.SingleOrDefault(x => x.ID == roomId);
                visitor.DepartureDate = null;
                _context.Add(visitor);
                _context.Rooms.Single(x => x.ID == roomId).IsBusy = true;
                _context.Update(_context.Rooms.Single(x => x.ID == roomId));

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(visitor);
        }

        // GET: Visitors/Edit/5
        public IActionResult Edit(Guid? roomId)
        {
            if (roomId == null)
            {
                return NotFound();
            }

            var visitor = _context.Visitors.Include(c => c.Room).SingleOrDefault(x => x.Room.ID == roomId && x.DepartureDate == null);
            if (visitor == null)
                return NotFound();


            visitor.DepartureDate = DateTime.UtcNow;
            visitor.Room.IsBusy = !visitor.Room.IsBusy;
            _context.Update(visitor);
            _context.SaveChangesAsync();

            double cost = 0;

            switch (visitor.Room.Type)
            {
                case RoomType.Standart:
                    cost += 100;
                    break;
                case RoomType.JuniorSuite:
                    cost += 200;
                    break;
                case RoomType.Lux:
                    cost += 300;
                    break;
            }

            cost += cost * 0.4 * (visitor.Room.NumberOfPlaces - 1);

            cost *= (visitor.DepartureDate - visitor.ArrivalDate).Value.Days;


            string result = $"Номер класса: {(typeof(RoomType).GetMember(visitor.Room.Type.ToString())[0].GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute)?.GetName()}; \r\n" +
                            $"Колличество мест - {visitor.Room.NumberOfPlaces}; \r\n" +
                            $"Колличество прожитых дней - {(visitor.DepartureDate - visitor.ArrivalDate).Value.Days}; \r\n" +
                            $"Полная стоимость проживания - {cost} у.е. \r\n";

            ViewBag.result = result;

            return View();
        }

       // GET: Visitors/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visitor = await _context.Visitors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (visitor == null)
            {
                return NotFound();
            }

            return View(visitor);
        }

        // POST: Visitors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var visitor = await _context.Visitors.FindAsync(id);
            _context.Visitors.Remove(visitor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitorExists(Guid id)
        {
            return _context.Visitors.Any(e => e.ID == id);
        }
    }
}

HotelProject/Views/Rooms/Create.cshtml
@model HotelProject.Models.Room

@{
    ViewData["Title"] = "Создать комнату";
}

<h2>Создать комнату</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<RoomType>()"></select>                
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPlaces" class="control-label"></label>
                <input asp-for="NumberOfPlaces" class="form-control" />
                <span asp-validation-for="NumberOfPlaces" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsBusy" /> @Html.DisplayNameFor(model => model.IsBusy)
                    </label>
                </div>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelProject/Views/Rooms/Delete.cshtml
@model HotelProject.Models.Room

@{
    ViewData["Title"] = "Удаление комнаты";
}

<h2>Удаление комнаты</h2>

<h3>Вы действительно хотите удалить эту комнату?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPlaces)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfPlaces)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsBusy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsBusy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

HotelProject/Views/Rooms/Details.cshtml
@model HotelProject.Models.Room

@{
    ViewData["Title"] = "Информация о комнате";
}

<h2>Информация о комнате</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPlaces)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfPlaces)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsBusy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsBusy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

HotelProject/Views/Rooms/Edit.cshtml
@model HotelProject.Models.Room

@{
    ViewData["Title"] = "Редактирование комнаты";
}

<h2>Редактирование комнаты</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<RoomType>()"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPlaces" class="control-label"></label>
                <input asp-for="NumberOfPlaces" class="form-control" />
                <span asp-validation-for="NumberOfPlaces" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IsBusy" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelProject/Views/Rooms/Index.cshtml
@model IEnumerable<HotelProject.Models.Room>

@{
    ViewData["Title"] = "Комнаты";
}

<h2>Комнаты</h2>

<p>
    <a asp-action="Create">Создать новую</a>
</p>

@using (Html.BeginForm())
{
    <p>
        Найти: @Html.TextBox("SearchString")
        <input type="submit" value="Поиск" />
    </p>
}

<table id="RoomTable" class="table">
    <thead>
        <tr>
            <th onclick="sortTable(0)">
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th onclick="sortTable(1)">
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th onclick="sortTable(2)">
                @Html.DisplayNameFor(model => model.NumberOfPlaces)
            </th>
            <th onclick="sortTable(3)">
                @Html.DisplayNameFor(model => model.IsBusy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfPlaces)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsBusy)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Правка</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Детали</a> |
                    @if (item.Visitors.Count == 0)
                    {
                        <a asp-action="Delete" asp-route-id="@item.ID">Удалить</a>  @Html.Raw("|")
                    }
                    @if (item.IsBusy)
                    {
                        <a asp-controller="Visitors" asp-action="Edit" asp-route-roomId="@item.ID">Выселить</a>
                    }
                    else
                    {
                        <a asp-controller="Visitors" asp-action="Create" asp-route-roomId="@item.ID">Заселить</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function sortTable(n) {
        var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("RoomTable");
        switching = true;
        dir = "asc";
        while (switching) {
            switching = false;
            rows = table.rows;
            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }
            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchcount++;
            } else {
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
</script>